---
USER_AGENT:
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36'
BLACK_DOMAIN:
  - 'www.google.gf'
  - 'www.google.io'
  - 'www.google.com.lc'

DOMAIN:
  'www.google.com'
URL_SEARCH:
  "https://{domain}/search?hl={language}&q={query}&btnG=Search&gbv=2&num=20&start={start}&source=lnms&tbm=nws"
